### ISSUE TITLE
Restructure Docs Repo

### ISSUE THREAD

**Issue by nebelsprachen** [integr8ly/user-documentation#105]
**Task**
Restructure repo. Possibly remove _partials folder and have content only in the pages folder. The goal is to present documentation both as a single page (massive assembly) _and_ as chapters/modules.

**Motivation**
This will help in improving findability and facilitate a more defined table of contents (nav.adoc).

**Issues Arising**
 * xref links will not resolve if not in the same assembly. xrefs will work in Antora, but not in Pantheon
 * attributes will have to be declared in each module. This might lead to errors and might be difficult to maintain

**Comment by pwright** [comment]
attributes can be set in antora.yml file, but not sure what to do about xrefs
