### ISSUE TITLE
2.1.0 release links

### ISSUE THREAD

**Issue by austincunningham** [integr8ly/user-documentation#119]
- fuse link is pointing at amq online
https://github.com/integr8ly/user-documentation/blame/master/modules/ROOT/pages/release-notes/master.adoc#L146

- amq online is using fuse version
https://github.com/integr8ly/user-documentation/blame/master/modules/ROOT/pages/release-notes/master.adoc#L152L154

**Comment by pwright** [comment]
@briandooley  not sure if these issues are still valid?
I'd suggest checking them on git lab

@austincunningham  as mentioned in readme for repo, this isn't an active repo, we just use it for publishing previews, we're not following issues here

**Comment by briandooley** [comment]
This looks to me like the github has been updated recently. The https://github.com/integr8ly/user-documentation/blame/master/modules/ROOT/pages/release-notes/master.adoc#L146 line just points to a heading.

Nevertheless, I checked. In the preview, the link to fuse online (https://access.redhat.com/documentation/en-us/red_hat_fuse/7.6/) points to the correct docs. 

The link to amq online currently is https://access.redhat.com/documentation/en-us/red_hat_amq/{fuse-version}/ .  This happens to go to the correct page as the fuse and amq versions are the same but the {fuse-version} should be removed.

**Comment by austincunningham** [comment]
closed out of date
